name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
        # Use npm ci to install dependencies from package-lock.json because it's faster than npm install and never updates package.json
      - run: npm ci
      - run: npm test
